# Generated by Django 3.1.4 on 2021-01-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='getcode',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
