# Generated by Django 3.1.4 on 2021-01-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_getcode_email_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='status',
        ),
        migrations.AlterField(
            model_name='getcode',
            name='email_confirmed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
