# Generated by Django 3.1.4 on 2021-01-09 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210105_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getcode',
            name='email_confirmed',
        ),
    ]
